### ISSUE TITLE
군인 추가.

### ISSUE THREAD

**Issue by jd730** [simnalamburt/snucse.gate#6]
충훈 : 17.12.13
주상 : 17.03.01
석원이형 : 17.05.03

**Comment by simnalamburt** [comment]
고마워용

**Comment by jd730** [comment]
동엽이 소집해제일 2016/02/16 이었답니다.

**Comment by jd730** [comment]
{ name: '신동빈', end: '02/15/2018' },

**Comment by jd730** [comment]
{ name: '이승민', end: '06/05/2018' },

**Comment by simnalamburt** [comment]
반영 완료
